openapi: 3.0.0
info:
  title: Task Manager API
  description: API para gestionar tareas con autenticación JWT
  version: 1.0.0
  contact:
    email: support@taskmanager.com

servers:
  - url: https://api.taskmanager.com/v1
    description: Servidor de producción
  - url: http://localhost:3000/v1
    description: Servidor de desarrollo

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              description: Mensaje de error descriptivo
            type:
              type: string
              description: Tipo de error
            details:
              type: object
              description: Detalles adicionales del error (opcional)

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "admin"
        password:
          type: string
          format: password
          example: "password"

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: Token JWT para autenticación

    Task:
      type: object
      properties:
        task_id:
          type: string
          format: uuid
          description: Identificador único de la tarea
        title:
          type: string
          description: Título de la tarea
        description:
          type: string
          description: Descripción detallada de la tarea
        status:
          type: string
          enum: [pending, in_progress, completed]
          description: Estado actual de la tarea
        created_at:
          type: string
          format: date-time
          description: Fecha de creación
        updated_at:
          type: string
          format: date-time
          description: Fecha de última actualización
        created_by:
          type: string
          description: ID del usuario que creó la tarea

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Implementar autenticación"
        description:
          type: string
          example: "Agregar sistema de autenticación JWT"
        status:
          type: string
          enum: [pending, in_progress, completed]
          default: pending
          example: "pending"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          example: "Título actualizado"
        description:
          type: string
          example: "Descripción actualizada"
        status:
          type: string
          enum: [pending, in_progress, completed]
          example: "completed"

paths:
  /login:
    post:
      summary: Autenticar usuario
      description: Autentica un usuario y devuelve un token JWT
      tags:
        - Autenticación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks:
    get:
      summary: Obtener todas las tareas
      description: Retorna la lista de todas las tareas
      tags:
        - Tareas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Crear nueva tarea
      description: Crea una nueva tarea
      tags:
        - Tareas
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Tarea creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: ID de la tarea

    get:
      summary: Obtener tarea por ID
      description: Retorna una tarea específica por su ID
      tags:
        - Tareas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Tarea encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Actualizar tarea
      description: Actualiza una tarea existente
      tags:
        - Tareas
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Tarea actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Eliminar tarea
      description: Elimina una tarea existente
      tags:
        - Tareas
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Tarea eliminada exitosamente
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 